name: release
on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path: build/libs/
      - name: run publish
        run: ./gradlew publishToSonatype
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ vars.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.MAVEN_PASSWORD }}
      - name: upload to modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: OVSgncUB
          version: ${{ github.ref_name }}
          loaders: fabric
          game-versions: 1.21.1
          files: build/libs/ghosty-${{ github.ref_name }}.jar
      - name: upload to github releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/libs/*.jar
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}